config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'dashboard#index' 

  resources :cars
  resources :clients
  resources :managers
  resources :sales
  resources :manufacturers
  resources :car_models
  resources :services
  resources :service_schedules
  resources :requested_services
  
end

app/models/service.rb
class Service < ActiveRecord::Base
    has_many :requested_services
    has_many :service_schedules, through: :requested_services
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
    def index
        @services = Service.all
    end

    def show
        @service = Service.find(params[:id])
    end

    def new
        @service = Service.new
    end

    def create
        @service = Service.new(service_params)

        if @service.save
            redirect_to @service
        else
            render :new
        end
    end

    def edit
        @service = Service.find(params[:id])
    end

    def update
        @service = Service.find(params[:id])

        if @service.update(service_params)
            redirect_to @service
        else
            render:edit
        end
    end

    def destroy
        @service = Service.find(params[:id])
        @service.destroy

        redirect_to root_path
    end

    private

    def service_params
        params.require(:service).permit(:name, :discription)
    end

end

app/views/services/_form.html.erb
<%= form_with model: service do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% service.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :discription %><br>
    <%= form.text_area :discription %>
    <% service.errors.full_messages_for(:discription).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/services/edit.html.erb
<h1>Edit Service Info</h1>

<%= render "form", service: @service %>

app/views/services/index.html.erb
<h2>Services</h2>
<% @services.each do |service| %>
    <%= service.name %>
    <%= link_to "Show", service_path(service) %>
    <%= link_to "Edit", edit_service_path(service) %> 
    <%= link_to "Destroy", service_path(service),
            method: :delete,
            data: { confirm: "Are you sure?" } %>
    <br/>
<% end %>

<%= link_to "New Service", new_service_path %>

<p> <%= link_to "Home", root_path %> </p>

app/views/services/new.html.erb
<h1>New Service</h1>

<%= render "form", service: @service %>

app/views/services/show.html.erb
<h2>Service info</h2>

Name: <%= @service.name %><br/>
Discription: <%= @service.discription %><br/>

<%= link_to "Back to list", services_path %>