config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'dashboard#index' 

  resources :cars
  resources :clients
  resources :managers
  resources :sales
  resources :manufacturers
  resources :car_models
  resources :services
  resources :service_schedules
  resources :requested_services
  
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
    def index
        @sales = Sale.recent
        @clients = Client.recent
        @managers = Sale.top_managers
        @cars = Car.recent
        @services_schedule = ServiceSchedule.incoming
    end
end

app/views/dashboard/_cars.html.erb
<table>
    <tr>
        <th> Car </th>
    </tr>
    <% @cars.each do |car| %>
    <tr>
        <td> <%= car.name %> </td>
        <% if show_controls%>
            <td> <%= link_to "Show", client_path(client) %> </td>
            <td> <%= link_to "Edit", edit_client_path(client)%></td>
            <td> <%= link_to "Destroy", client_path(client),
                    method: :delete,
                    data: { confirm: "Are you sure?" } %> </td>
            <br/>
        <% end %>
    <%end%>
    </tr>
</table>

app/views/dashboard/_clients.html.erb
<table>
    <tr>
        <th> Client </th>
    </tr>
    <% @clients.each do |client| %>
    <tr>
        <td> <%= client.full_name %> </td>
        <% if show_controls%>
            <td> <%= link_to "Show", client_path(client) %> </td>
            <td> <%= link_to "Edit", edit_client_path(client)%></td>
            <td> <%= link_to "Destroy", client_path(client),
                    method: :delete,
                    data: { confirm: "Are you sure?" } %> </td>
            <br/>
        <% end %>
    <%end%>
    </tr>
</table>

app/views/dashboard/_links.html.erb
<br/>
<p> <%= link_to "Cars", cars_path %> </p>
<p> <%= link_to "Managers", managers_path %> </p>
<p> <%= link_to "Manufacturers", manufacturers_path %> </p>
<p> <%= link_to "Car Models", car_models_path %> </p>
<p> <%= link_to "Services", services_path %> </p>
<p> <%= link_to "Service Schedules", service_schedules_path %> </p>

app/views/dashboard/_managers.html.erb
<table>
    <tr>
        <th> Manager </th>
        <th> Sales </th>
    </tr>
    <% @managers.each do |manager| %>
        <tr>
            <td> <%= manager[:full_name] %> </td>
            <td> <%= manager[:count] %> </td>
            <% if show_controls %>
                <td> <%= link_to "Show", manager_path(manager[:id]) %>
                <td> <%= link_to "Edit", edit_manager_path(manager[:id]) %> </td>
                <td> <%= link_to "Destroy", manager_path(manager[:id]),
                    method: :delete,
                    data: { confirm: "Are you sure?" } %> </td> 
                <br/>
            <% end %>
        </tr>
    <% end %>
</table>

app/views/dashboard/_sales.html.erb
<table>
    <tr>
        <th> Car </th>
        <th> Client </th>
        <th> Manager </th>
        <th> Purchase Date </th>
    </tr>
    <% @sales.each do |sale| %>
        <tr>
            <td> <%= sale.car.name %> </td>
            <td> <%= sale.client.full_name %> </td>
            <td> <%= sale.manager.full_name %> </td>
            <td> <%= sale.purchase_date.strftime("%d.%m.%Y") %> </td>
            <% if show_controls %>
                <td> <%= link_to "Show", sale_path(sale) %>
                <td> <%= link_to "Edit", edit_sale_path(sale) %> </td>
                <td> <%= link_to "Destroy", sale_path(sale),
                    method: :delete,
                    data: { confirm: "Are you sure?" } %> </td> 
                <br/>
            <% end %>
        </tr>
    <% end %>
</table>
    

app/views/dashboard/_services_schedule.html.erb
<table>
    <tr>
        <th> Car Name </th>
        <th> Manager </th>
        <th> Services </th>
        <th> Date </th>
    </tr>
    <% @services_schedule.each do |service_schedule| %>
        <tr>
            <td> <%= service_schedule.car.name %> </td>
            <td> <%= service_schedule.manager.full_name %> </td>
            <td> <%= service_schedule.services.pluck(:name) %> </td>
            <td> <%= service_schedule.service_date %> </td>
            <% if show_controls %>
                <td> <%= link_to "Show", service_schedule_path(service_schedule) %>
                <td> <%= link_to "Edit", edit_service_schedule_path(service_schedule) %> </td>
                <td> <%= link_to "Destroy", service_schedule_path(service_schedule),
                    method: :delete,
                    data: { confirm: "Are you sure?" } %> </td> 
                <br/>
            <% end %>
        </tr>
    <% end %>
</table>

app/views/dashboard/index.html.erb
<h2>Last sales</h2>

<%= render "sales", sale: @sale, show_controls: false %>
<%= link_to "Show All Sales", sales_path %>

<h2>New cars</h2>

<%= render "cars", car: @car, show_controls: false %>
<%= link_to "Show All Cars", cars_path %>

<h2>Top managers</h2>

<%= render "managers", manager: @manager, show_controls: false %>
<%= link_to "Show All Managers", managers_path %>

<h2>Last clients</h2>

<%= render "clients", client: @client, show_controls: false %>
<%= link_to "Show All Clients", clients_path %>

<h2>Incoming Services Schedule</h2>

<%= render "services_schedule", service_schedule: @service_schedule, show_controls: false %>
<%= link_to "Show All Services Schedule", service_schedules_path %>

<%= render "links" %>