config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'dashboard#index' 

  resources :cars
  resources :clients
  resources :managers
  resources :sales
  resources :manufacturers
  resources :car_models
  resources :services
  resources :service_schedules
  resources :requested_services
  
end

app/models/manager.rb
class Manager < ActiveRecord::Base

    def full_name
        "#{first_name} #{last_name}"
    end 
end

app/controllers/managers_controller.rb
class ManagersController < ApplicationController
    def index 
        @managers = Manager.all
    end

    def show
        @manager = Manager.find(params[:id])
    end 

    def new
        @manager = Manager.new
    end

    def create 
        @manager = Manager.new(manager_params)

        if @manager.save
            redirect_to @manager
        else 
            render :new
        end
    end

    def edit
        @manager = Manager.find(params[:id])
    end 

    def update
        @manager = Manager.find(params[:id])

        if @manager.update(manager_params)
            redirect_to @manager
        else 
            render :edit
        end
    end

    def destroy
        @manager = Manager.find(params[:id])
        @manager.destroy
    
        redirect_to root_path
    end

    private
    
    def manager_params
        params.require(:manager).permit(:first_name, :last_name)
    end
end

app/views/managers/_form.html.erb
<%= form_with model: manager do |form| %>
  <div>
    <%= form.label :first_name %><br>
    <%= form.text_field :first_name %>
    <% manager.errors.full_messages_for(:first_name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :last_name %><br>
    <%= form.text_area :last_name %>
    <% manager.errors.full_messages_for(:last_name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/managers/edit.html.erb
<h1>Edit Manager Info</h1>

<%= render "form", manager: @manager %>

app/views/managers/index.html.erb
<h2> Managers </h2>

<% @managers.each do |manager| %>
    <%= manager.id %>
    <%= manager.full_name %>
    <%= link_to "Show", manager_path(manager) %>
    <%= link_to "Edit", edit_manager_path(manager)%>
    <%= link_to "Destroy", manager_path(manager),
            method: :delete,
            data: { confirm: "Are you sure?" } %><br/>
<% end %>

<%= link_to "New Manager", new_manager_path %>

<p> <%= link_to "Home", root_path %> </p>

app/views/managers/new.html.erb
<h1>New Manager</h1>

<%= form_with model: @manager do |form| %>
  <div>
    <%= form.label :first_name %><br>
    <%= form.text_field :first_name %>
    <% @manager.errors.full_messages_for(:first_name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

 <div>
    <%= form.label :last_name %><br>
    <%= form.text_field :last_name %>
    <% @manager.errors.full_messages_for(:last_name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/managers/show.html.erb
<h2>Manager info</h2>

№: <%= @manager.id %><br/>
Name: <%= @manager.full_name %><br/>

<%= link_to "Back to list", managers_path %>