config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'dashboard#index' 

  resources :cars
  resources :clients
  resources :managers
  resources :sales
  resources :manufacturers
  resources :car_models
  resources :services
  resources :service_schedules
  resources :requested_services
  
end

app/models/car.rb
class Car < ActiveRecord::Base
    validates :colour, presence: true
    validates :price, presence: true
    validates :vin, presence: true, uniqueness: true

    belongs_to :car_model
    has_one :sale

    def name 
        "#{car_model.name_with_manufacturer} (VIN: #{vin})"
    end

    scope :recent, -> {order(created_at: :desc).limit(5) }
    scope :available, -> {left_outer_joins(:sale).where("sales.car_id is null")}
end 

app/controllers/cars_controller.rb
class CarsController < ApplicationController
    def index
        @cars = Car.all
    end

    def show
        @car = Car.find(params[:id])
    end

    def new
        @car = Car.new
        fill_dictionaries
    end

    def create
        @car = Car.new(car_params)
    
        if @car.save
          redirect_to @car
        else
          render :new
        end
    end

    def edit
        @car = Car.find(params[:id])
        fill_dictionaries
    end
    
    def update
        @car = Car.find(params[:id])
        
        if @car.update(car_params)
            redirect_to @car
        else
            render :edit
        end
    end 

    def destroy
        @car = Car.find(params[:id])
        @car.destroy
    
        redirect_to root_path
    end
      
    private
    
    def car_params
      params.require(:car).permit(:colour, :price, :vin, :car_model_id)
    end

    def fill_dictionaries
        @car_models = CarModel.all
        @manufacturers = Manufacturer.all
    end

end

app/views/cars/_form.html.erb
<%= form_with model: car do |form| %>
  <div>
    <%= form.label :name_with_manufacturer %><br>
    <%= form.collection_select :car_model_id, car_models, :id, :name_with_manufacturer %>
    <% car.errors.full_messages_for(:car_model_id).each do |message| %>
      <div> <%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :colour %><br>
    <%= form.text_area :colour %>
    <% car.errors.full_messages_for(:colour).each do |message| %>
      <div> <%= message %> </div>
    <% end %>
  </div>

  <div>
    <%= form.label :price %><br>
    <%= form.text_area :price %>
    <% car.errors.full_messages_for(:price).each do |message| %>
      <div> <%= message %> </div>
    <% end %>
  </div>

  <div>
    <%= form.label :vin %><br>
    <%= form.text_area :vin %>
    <% car.errors.full_messages_for(:vin).each do |message| %>
      <div> <%= message %> </div>
    <% end %>
  </div>


  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Edit Car Info</h1>

<%= render "form", car: @car, car_models: @car_models, manufacturers: @manufacturers %>

app/views/cars/index.html.erb
<h2>Cars</h2>
<% @cars.each do |car| %>
    <%= car.id %>
    <%= car.name %>
    <%= link_to "Show", car_path(car) %>
    <%= link_to "Edit", edit_car_path(car) %> 
    <%= link_to "Destroy", car_path(car),
            method: :delete,
            data: { confirm: "Are you sure?" } %>
    <br/>
<% end %>

<%= link_to "New Car", new_car_path %>

<p> <%= link_to "Home", root_path %> </p>

app/views/cars/new.html.erb
<h1>New Car</h1>

<%= render "form", car: @car, car_models: @car_models, manufacturers: @manufacturers %>

app/views/cars/show.html.erb
<h2>Car info</h2>

№: <%= @car.id %><br/>
Name: <%= @car.name %><br/>
Colour: <%= @car.colour %><br/>
Price: <%= @car.price %><br/>
Vin: <%= @car.vin %><br/>

<%= link_to "Back to list", cars_path %>